export enum actionTypes {
  REQ_TO_UPLOAD_FILE = 'REQ_TO_UPLOAD_FILE',
  FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS',
  FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE',
  REQ_TO_ENCRYPT = 'REQ_TO_ENCRYPT',
  ENCRYPT_SUCCESS = 'ENCRYPT_SUCCESS',
  ENCRYPT_FAILURE = 'ENCRYPT_FAILURE',
  REQ_TO_GET_FILE = 'REQ_TO_GET_FILE',
  REQ_TO_DECRYPT = 'REQ_TO_DECRYPT',
  DECRYPT_SUCCESS = 'DECRYPT_SUCCESS',
  DECRYPT_FAILURE = 'DECRYPT_FAILURE',
  SWITCH_LANGUAGE = 'SWITCH_LANGUAGE',
}
